### ISSUE TITLE
Balance & Address corrections

### ISSUE THREAD

**Issue by a5kold** [parsec-labs/project-alice#11]
1. If we are using ETH for transactions we should use eth-icon for it, not PSC
2. Fix center alignment of the address
3. Add hover on copy icon

![2](https://user-images.githubusercontent.com/17252256/42045539-6c40b55c-7b04-11e8-8266-bd63325117b3.PNG)

**Comment by maxkudla** [comment]
> If we are using ETH for transactions we should use eth-icon for it, not PSC

@a5kold Do we have this one?

**Comment by sunify** [comment]
No. We'll merge #3 soon

**Comment by a5kold** [comment]
https://drive.google.com/drive/folders/10f7fR2M7G_4gXiawNweMnHWY3NdS6vkl?usp=sharing
eth-icon in svg folder, if needed
