### ISSUE TITLE
Add an info pop-up after successful submission of transaction

### ISSUE THREAD

**Issue by mateleshkavo** [parsec-labs/project-alice#8]
As a visitor I want to see an info pop-up after I have successfully submitted a transaction.

**Comment by maxkudla** [comment]
After successfully submitted a transaction we put this one into the transaction list with pending status... so do we need duplicate this info with a pop-up?

**Comment by maxkudla** [comment]
@mateleshkavo @a5kold Do we really need this pop-up?

**Comment by mateleshkavo** [comment]
After you submit a transaction transaction is added to the list, however it's not visible if you don't scroll down. So it feels like nothing happened. For consistent UX I would suggest to add some pop-up or at least info message that transaction was sent.

**Comment by sunify** [comment]
Please, no popup. A message is ok. A thing that will cover entire screen — no no.

We need Alice also for ourselves and we need to send a lot of transactions sometimes. Popup will add unnecessary action during the test

**Comment by maxkudla** [comment]
@mateleshkavo Transaction is added to the top of the list, as the first row. So u always can catch it

**Comment by sunify** [comment]
As an option. We can scroll the page to place at the bottom of the window. So we'll have form and transactions list in the viewport

**Comment by mateleshkavo** [comment]
@maxkudla please open the page, don't scroll to the bottom, send the tx -> you don't see any transactions or any movement (or at least I don't see on my screen resolution). @sunify agree, message will be fine

**Comment by maxkudla** [comment]
@a5kold Could u provide design pls?

**Comment by a5kold** [comment]
Can we add the same "success message" as when you copy the address? Above the send button.

**Comment by maxkudla** [comment]
> Can we add the same "success message" as when you copy the address? Above the send button.

@a5kold yes, but it'll be gr8 to show tx info (from, to, value)... in the message. What do u think?
